version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: jobnest-app
    container_name: jobnest-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - jobnest

  web:
    image: nginx:alpine
    container_name: jobnest-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - jobnest

  node:
    image: node:20
    container_name: jobnest-node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - jobnest

  db:
    image: postgres:14
    container_name: jobnest-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobnest
      POSTGRES_USER: jobnest
      POSTGRES_PASSWORD: jobnest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jobnest

networks:
  jobnest:
    driver: bridge

volumes:
  db_data:
